;===PROG3.ASM=====================================
LIST P=16F628A
INCLUDE "P16F628A.INC"
__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF& _LVP_OFF & _CP_OFF
ORG h'0000'
CLRF PORTB
BANKSEL TRISB
CLRF TRISB
MOVLW h'FF'
MOVWF TRISA
BANKSEL PORTB
MOVLW h'07'
MOVWF CMCON
STARTLABEL
MOVF PORTA, W
MOVWF PORTB
GOTO STARTLABEL
END
;---------------------------
